name: app
description: connect app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-406.0.dev <3.0.0'

dependencies:
  animated_theme_switcher: ^2.0.7
  collection: ^1.16.0
  dio: ^4.0.6
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.1
  form_builder_validators: ^8.3.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  functional_widget_annotation: ^0.10.0
  gap: ^2.0.0
  go_router: ^5.1.1
  hooks_riverpod: ^2.1.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  slang: ^3.0.0
  slang_build_runner: ^3.0.0
  slang_flutter: ^3.0.0
  tuple: ^2.0.1
  riverpod_annotation: ^1.0.6

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.4.0
  flutter_test:
    sdk: flutter
  functional_widget: ^0.10.1
  json_serializable: ^6.4.0
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true