name: site
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^1.0.4
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  functional_widget_annotation: ^0.10.0
  gap: ^2.0.0
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  slang: ^2.8.0

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.17.0
  flutter_test:
    sdk: flutter
  functional_widget: ^0.10.0

flutter:
  uses-material-design: true
